### PR TITLE
Enable sbt cross-build for Scala 2.12

### PR DESCRIPTION
**Pull request by spyk**
- Update sbt dependencies for 2.12
- Update 2.11 Scala version to 2.11.11
- Update sbt plugins to latest versions

To cross compile, you need to run `sbt +package` or `sbt +publish`

### CODE REVIEW

**Comment by nathankleyn** [comment]
Wow, thanks @spyk! I'll try to have a look at this properly as soon as I can. 👍

**Review by nathankleyn — APPROVED** [review]
Thank-you very much for this @spyk, this is a really helpful submission! I'll try to publish a new version of gander cross-compiled for 2.12/2.11 ASAP for you. 👍

**Comment by nathankleyn** [comment]
@spyk Published v1.4 to Maven Central now, should hopefully be available soon for 2.12 and 2.11 - many thanks for your contribution!

http://central.maven.org/maven2/com/intenthq/gander_2.11/1.4/
http://central.maven.org/maven2/com/intenthq/gander_2.12/1.4/

**Comment by spyk** [comment]
Wow excellent, thank you very much for the quick response!

**Pull request merged**
